name: Sync foo-space
on:
  push:
    branches:
      - submodules
  workflow_dispatch:

env:
  TARGET_OWNER: larshinueber
  TARGET_REPO: foo-space

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_OWNER }}/${{ env.TARGET_REPO }}
          token: ${{ secrets.GH_PAT }}
          ref: submodules
      
      - name: Fetch new commits
        run: |

            git submodule update --init --recursive
            git submodule update --recursive --remote
            
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update submodule to ${{ github.event.after }}"
          
